### ISSUE TITLE
服务器未知错误

### ISSUE THREAD

**Issue by ZhaoYaoran** [qwe305/dms#1]
您好，我有一些问题想请教您。你可以帮帮我吗。如果可以的话能不能加您一个好友。拜托了，大佬。

**Comment by 1078250864** [comment]
联系方式如同，QQ。拜托了大佬，感激不尽。

**Comment by ZhaoYaoran** [comment]
联系方式就是名称，QQ。拜托了大佬，感激不尽。

**Comment by 1078250864** [comment]
![image](https://user-images.githubusercontent.com/74187666/134926795-10fa9774-206b-42e2-a55a-d73792c578e3.png)

**Comment by 1078250864** [comment]
![image](https://user-images.githubusercontent.com/74187666/134927152-dbf4613c-df77-4536-9cd5-325ec3e1d3fb.png)

**Comment by ZhaoYaoran** [comment]
![image](https://user-images.githubusercontent.com/74187666/134928227-f8f9fc8f-f512-4cab-a955-bbc27ed0a0ad.png)

**Comment by ZhaoYaoran** [comment]
![image](https://user-images.githubusercontent.com/74187666/134928309-def1472c-93de-4c62-993b-6e282c52d21e.png)
![image](https://user-images.githubusercontent.com/74187666/134928336-36adb89e-c610-4a10-a932-b72439cc0187.png)

**Comment by qwe305** [comment]
需要redis，安装redis教程 https://www.runoob.com/redis/redis-install.html
